import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
https://github.com/lavemile02-afk/Literature-Graph-for-Obsidian

Literature Graph is released under the MIT License. It bundles, among others:
- PixiJS (https://pixijs.com), MIT License, Copyright (c) 2013-2023 Mathew Groves, Chad Engler
- d3-force (https://d3js.org/d3-force), ISC License, Copyright 2010-2021 Mike Bostock
- umap-js (https://github.com/PAIR-code/umap-js), Apache License 2.0, Copyright 2019 Google LLC
Its idle animations are adapted from thinking-orbs (https://github.com/Jakubantalik/thinking-orbs),
MIT License, Copyright (c) 2026 Jakub Antalik.
The licenses of all bundled packages are in THIRD-PARTY-NOTICES.md in the repository.
*/
`;

const prod = process.argv[2] === 'production';

// The layout's web worker (src/layoutWorker.ts) is bundled on its own and
// embedded in main.js as text: a plugin is a single file, so the worker is
// started from a Blob.
const layoutWorker = {
	name: 'layout-worker',
	setup(build) {
		build.onResolve({ filter: /^layout-worker:code$/ }, (args) => ({ path: args.path, namespace: 'layout-worker' }));
		build.onLoad({ filter: /.*/, namespace: 'layout-worker' }, async () => {
			const result = await esbuild.build({
				entryPoints: ['src/layoutWorker.ts'],
				bundle: true,
				write: false,
				format: 'iife',
				target: 'es2021',
				minify: prod,
				metafile: true,
				logLevel: 'silent',
			});
			return {
				contents: result.outputFiles[0].text,
				loader: 'text',
				watchFiles: Object.keys(result.metafile.inputs),
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [layoutWorker],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
